# Generated by Django 3.1.7 on 2022-11-07 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=100)),
                ('course_type', models.CharField(max_length=100)),
                ('duration', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='department',
            fields=[
                ('dept_id', models.AutoField(primary_key=True, serialize=False)),
                ('dept_name', models.CharField(max_length=100)),
                ('dept_email', models.EmailField(max_length=70)),
                ('dept_phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='election',
            fields=[
                ('elect_id', models.AutoField(primary_key=True, serialize=False)),
                ('elect_date', models.DateField()),
                ('elect_nomi_start_date', models.DateField()),
                ('elect_nomi_end_date', models.DateField()),
                ('elect_nomi_withdrawal_end_date', models.DateField()),
                ('elect_status', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('username', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
                ('user_type', models.IntegerField(choices=[(0, 'admin'), (2, 'department'), (3, 'student')])),
                ('user_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='panel',
            fields=[
                ('panel_id', models.AutoField(primary_key=True, serialize=False)),
                ('panel_post', models.CharField(max_length=100)),
                ('panel_type', models.IntegerField(choices=[(0, 'General'), (1, 'female')], default=0)),
                ('panel_status', models.IntegerField(choices=[(0, 'inactive'), (1, 'active')], default=1)),
                ('panel_year', models.IntegerField(choices=[(0, 'all'), (1, '1st year'), (2, '2nd year'), (3, '3rd year'), (4, '4th year')], default=0)),
                ('panel_votes', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('stud_id', models.AutoField(primary_key=True, serialize=False)),
                ('stud_fname', models.CharField(max_length=100)),
                ('stud_mname', models.CharField(max_length=100, null=True)),
                ('stud_lname', models.CharField(max_length=100)),
                ('stud_dob', models.DateField(null=True)),
                ('stud_gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('stud_email', models.EmailField(max_length=70)),
                ('stud_mob', models.CharField(max_length=11, null=True)),
                ('stud_start_date', models.DateField()),
                ('stud_end_date', models.DateField()),
                ('stud_course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.course')),
            ],
        ),
        migrations.CreateModel(
            name='panel_specific',
            fields=[
                ('specific_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.course')),
                ('panel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.panel')),
            ],
        ),
        migrations.CreateModel(
            name='election_panel',
            fields=[
                ('ep_id', models.AutoField(primary_key=True, serialize=False)),
                ('elect_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.election')),
                ('panel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.panel')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='dept_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.department'),
        ),
    ]
